cart/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _

from cart import views


app_name = "cart"


urlpatterns = [
    path("add/<int:product_id>/", views.cart_add, name="cart_add"),
    path("remove/<int:product_id>/", views.cart_remove, name="cart_remove"),
    path(_("detail/"), views.cart_detail, name="cart_detail"),
]

coupons/urls.py
from django.urls import path

from coupons import views

app_name = 'coupons'


urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

from payment import webhooks

urlpatterns = i18n_patterns(
    path("admin/", admin.site.urls),
    path(_("cart/"), include("cart.urls", namespace="cart")),
    path(_("orders/"), include("orders.urls", namespace="orders")),
    path(_("payment/"), include("payment.urls", namespace="payment")),
    path(_("coupons/"), include("coupons.urls", namespace="coupons")),
    path("rosetta/", include("rosetta.urls")),
    path("", include("shop.urls", namespace="shop")),
)

urlpatterns += [
    path("webhook/", webhooks.stripe_webhook, 
                     name="stripe-webhook"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _
from orders import views

app_name = 'orders'


urlpatterns = [
    path(_('create/'), views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail,
                                        name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.generate_pdf_for_order,
                                            name='admin_order_pdf'),
]

shop/urls.py
from django.urls import path
from shop import views


app_name = "shop"


urlpatterns = [
    path("", views.product_list, name="product_list"),
    path("<slug:category_slug>/", views.product_list, name="product_list_by_category"),
    path("<int:id>/<slug:slug>/", views.product_detail, name="detail_product")
]

cart/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _


class CartAddProductForm(forms.Form):
    PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
                                      coerce=int, label=_('Quantity'))
    override = forms.BooleanField(
        initial=False, required=False, widget=forms.HiddenInput
    )

cart/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST

from cart.cart import Cart
from cart.forms import CartAddProductForm
from coupons.forms import CouponApplyForm
from shop.models import Product
from shop.recommender import Recommender


@require_POST
def cart_add(request: HttpRequest, product_id: int):
    cart = Cart(request)
    product = get_object_or_404(Product, pk=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cart.add(
            product=product,
            quantity=form.cleaned_data["quantity"],
            override_quantity=form.cleaned_data["override"],
        )
    return redirect("cart:cart_detail")


@require_POST
def cart_remove(request: HttpRequest, product_id: int):
    cart = Cart(request)
    product = get_object_or_404(Product, pk=product_id)
    cart.remove(product=product)
    return redirect("cart:cart_detail")


def cart_detail(request: HttpRequest) -> HttpResponse:
    cart = Cart(request)
    r = Recommender()
    for item in cart:
        item["update_quantity_form"] = CartAddProductForm(
            initial={"quantity": item["quantity"], "override": True}
        )
    recommended_products = r.suggest_products_for(
        [cart_item['product'] for cart_item in cart], 4
    )
    coupon_apply_form = CouponApplyForm()
    return render(request,
                  "cart/detail.html",
                  {"cart": cart,
                   'coupon_apply_form': coupon_apply_form,
                   'recommended_products': recommended_products})

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load i18n %}
{% load recommended_tag %}
{% load static %}

{% block title %}
  {% trans "Your shopping cart" %}
{% endblock %}

{% block content %}
  <h1>{% trans "Your shopping cart" %}</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>{% trans "Image" %}</th>
        <th>{% trans "Product" %}</th>
        <th>{% trans "Quantity" %}</th>
        <th>{% trans "Remove" %}</th>
        <th>{% trans "Unit price" %}</th>
        <th>{% trans "Price" %}</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}
                {% else %}{% static "img/no_image.png" %}{% endif %}">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form action="{% url "cart:cart_add" product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.override }}
                <input type="submit" value="{% trans "Update" %}">
                {% csrf_token %}
              </form>
            </td>
            <td>
              <form action="{% url "cart:cart_remove" product.id %}" method="post">
                <input type="submit" value="{% trans "Remove" %}">
                {% csrf_token %}
              </form>
            </td>
            <td class="num" style="text-align: center;">${{ item.price }}</td>
            <td class="num" style="text-align: center;">${{ item.total_price }}</td>
          </tr>
        {% endwith %}
      {% empty %}
      <h1 style="text-align: center;">Cart is empty</h1>
      {% endfor %}
      {% if cart.coupon %}
        <tr class="subtotal">
          <td>{% trans "Subtotal" %}</td>
          <td colspan="4"></td>
          <td class="num">${{ cart.get_total_price|floatformat:2 }}</td>
        </tr>
        <tr>
          <td>
            "{{ cart.coupon.code }}" {% trans "coupon" %}
            ({{ cart.coupon.discount }}% off)
          </td>
          <td colspan="4"></td>
          <td class="num neg">
            - ${{ cart.get_discount|floatformat:2 }}
          </td>
        </tr>
        
      {% endif %}
      <tr class="total">
        <td>{% trans "Total" %}</td>
        <td colspan="4"></td>
        <td class="num">${{ cart.get_total_price_after_discount|floatformat:2 }}</td>
      </tr>
    </tbody>
  </table>
  {% get_recommended_products recommended_products=recommended_products%}
  <p>{% trans "Apply a coupon:" %}</p>
  <form action="{% url "coupons:apply" %}" method="post">
    {{ coupon_apply_form }}
    <input type="submit" value="{% trans "Apply" %}">
    {% csrf_token %}
  </form>
  <p class="text-right">
    <a href="{% url "shop:product_list" %}" class="button
    light">{% trans "Continue shopping" %}</a>
    <a href="{% url "orders:order_create" %}" id="checkout" class="button">{% trans "Checkout" %}</a>
  </p>
{% endblock %}
<script>
    let table = document.getElementsByTagName('table')[0]
    let checkoutBtn = document.getElementById('checkout')
    
    if(!parseInt({{ cart|length }})) {
      table.hidden = true
      checkoutBtn.hidden = true
    }
</script>